# What is new in Python3?

Python 3 features we could use in RHEL 8.

## RHEL 8 and Python 3

RHEL 8 uses Python 3.6 and Python 3.8 is available since RHEL 8.3, but it is not installed by default (it is possible to install python38-* RPM packages there). So we will be limited by Python 3.6 for very long time. Fedora 32 uses Python 3.8. Fedora 33 uses Python 3.9.

## Keyed Argument After *args

In [61]:
def old_method(foo, *args, **kwargs):
    print(foo, args, kwargs)

    
def func_example_01(foo, *args, bar=None):
    """
    Function demonstrating keyed argument after *args. It wasn't possible in Python 2.7
    """
    print(foo, args, bar)

    
func_example_01(1, 2, 3, 4, 5, bar='Baaaar')
func_example_01(1, 2, 30)
func_example_01(1)


1 (2, 3, 4, 5) Baaaar
1 (2, 30) None
1 () None


## Key-only arguments

In [63]:
def func_example_00(a, b, *, c, d):
    """
    Arguments c and d has to be keyed
    """
    print(a, b, c, d)

func_example_00(1, 2, c=3, d=4)
func_example_00(1, b=2, c=3, d=4)

# Example of wrong usage
try:
    func_example_00(1, 2, 3, 4)
except TypeError as err:
    print(err)

1 2 3 4
1 2 3 4
func_example_00() takes 2 positional arguments but 4 were given


## Extended Iterable Unpacking

In [65]:
def func_example_02():
    """
    Function returning tuple
    """
    return 1, 2, 3, 4

first, *rest = func_example_02()
print(first, rest)

first, second, third, fourth, *rest = func_example_02()
print(first, second, third, fourth, rest)

first, *rest, last = func_example_02()
print(first, rest, last)

*rest, last = func_example_02()
print(rest, last)

all = func_example_02()
print(all)

1 [2, 3, 4]
1 2 3 4 []
1 [2, 3] 4
[1, 2, 3] 4
(1, 2, 3, 4)


## Additional Unpacking Generalizations

It is possible to use * and ** unpacking in function calls.

In [44]:
print(*[1], *[2], 3, *[4, 5])
l = [10, 20, 30]
print(*l, *l)

def func_example_02_01(a, b, c, d):
    print(a, b, c, d)

func_example_02_01(**{'a': 1, 'c': 3}, **{'b': 2, 'd': 4})

1 2 3 4 5
10 20 30 10 20 30
1 2 3 4


## Type Hints

In [66]:
# Annotation of method
def func_example_03(foo: str, bar: float) -> None:
    """
    Simple doc string for this function.
    :param foo: The foo argument
    :param bar: The bar argument
    """
    print(foo, bar)


# The Python is still dynamic programming language
func_example_03('foo', 3.1415)
func_example_03('foo', 123)

# But e.g. PyCharm will show some warning in following line
func_example_03(1, None)
print(help(func_example_03))


# Annotation of class variables
class Foo(object):
    foo: Dict[str, int] = {}

# Annotations are available in __annotations__
f = Foo()
print(f.__annotations__)


# Example of annotation, when more possible types is possible to use
from typing import Union
def func_example_03_01(foo: Union[str, int]) -> None:
    print(foo)


# Annotation of variable
primes: List[int] = []
primes.append('Hi')

foo 3.1415
foo 123
1 None
Help on function func_example_03 in module __main__:

func_example_03(foo: str, bar: float) -> None
    Simple doc string for this function.
    :param foo: The foo argument
    :param bar: The bar argument

None
{'foo': typing.Dict[str, int]}


## Anotation of Function Arguments

In [14]:
def func_example_04(foo: "foo argument", bar: "bar argument") -> None:
    print(foo, bar)

func_example_04('foo', 'bar')


foo bar


## New Keyword *nonlocal*

Similar to *global* keyword. It is possible to reference variable in outer method from nested method.

In [73]:
x = 0

def foo():
    global x
    x = 10

def outer():
    x = 1
    def inner():
        nonlocal x
        x = 2
        print("inner:", x)

    inner()
    print("outer:", x)

foo()
print("global:", x)
outer()
print("global:", x)


global: 10
inner: 2
outer: 2
global: 10


## The u"unicode" syntax is accepted (again)

In [36]:
s1 = "string"
print(type(s1))

s2 = u"string"  # Added back due to compatibility with Python 2.7
print(type(s2))


<class 'str'>
<class 'str'>


## Delegating to a Subgenerator

In [68]:
from typing import *

def all_chars(s: str) -> Generator[str, None, None]:
    yield from s.lower()
    yield from s.upper()

print(list(all_chars('Python')))

['p', 'y', 't', 'h', 'o', 'n', 'P', 'Y', 'T', 'H', 'O', 'N']


## Coroutines with async and await syntax

Jupyter doesn't like async/await for some reason...

```python
import asyncio

async def coro(name, lock):
    print('coro {}: waiting for lock'.format(name))
    async with lock:
        print('coro {}: holding the lock'.format(name))
        await asyncio.sleep(1)
        print('coro {}: releasing the lock'.format(name))

loop = asyncio.get_event_loop()
lock = asyncio.Lock()
coros = asyncio.gather(coro(1, lock), coro(2, lock))
try:
    loop.run_until_complete(coros)
finally:
    loop.close()
```

## Matrix multiplication

In [27]:
import numpy

x = numpy.ones(3)
print(x)

m = numpy.eye(3)
print(m)

r = x @ m
print(r)

[1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]


## Formated string literals

In [69]:
import decimal

name = "Joe"
print(f"He said that his name is {name}")

width = 10
precision = 2
value = decimal.Decimal("3.1415926535897932384626433")
print(f"result: {value:{width}.{precision}}")

He said that his name is Joe
result:        3.1


## Underscores in Numeric Literals

In [37]:
value = 1_000_000_000
another_value = 0x_FF_FF_FF_FF

print(value)
print(another_value)

1000000000
4294967295


## Asynchronous Generators

Jupyter does not like anything asynchronous

```python
import asyncio

async def ticker(delay, to):
    """Yield numbers from 0 to *to* every *delay* seconds."""
    for i in range(to):
        yield i
        await asyncio.sleep(delay)


async def iter_items():
    async for item in ticker(1, 5):
        print(item)


def main():
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(iter_items())
    finally:
        loop.close()


if __name__ == '__main__':
    main()
```

## Asynchronous Comprehensions

```python
result = [i async for i in aiter() if i % 2]

result = [await fun() for fun in funcs if await condition()]
```

## Python 3.8 Assigment expressions

In [71]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

if (my_list_len := len(my_list)) > 8:
    print(f"List is too long ({my_list_len} elements, expected <= 8)")

List is too long (11 elements, expected <= 8)


## Python 3.8 Positional-only parameters

In [72]:
def func_example_05(a, b, /, c, d, *, e, f) -> None:
    print(a, b, c, d, e, f)

func_example_05(10, 20, 30, d=40, e=50, f=60)
func_example_05(10, 20, c=30, d=40, e=50, f=60)

# Example of wrong usage
try:
    func_example_05(10, b=20, c=30, d=40, e=50, f=60)
except TypeError as err:
    print(err)

# Another wrong usage
# try:
#     func_example_05(10, 20, 30, 40, 50, f=60)
# except TypeError as err:
#     print(err)

10 20 30 40 50 60
10 20 30 40 50 60
func_example_05() got some positional-only arguments passed as keyword arguments: 'b'
